SELECT ROUTINE_SCHEMA + '.' + ROUTINE_NAME AS [Object_Name]
	,ROUTINE_TYPE
	,CREATED
	,LAST_ALTERED
FROM INFORMATION_SCHEMA.ROUTINES
WHERE ROUTINE_NAME NOT LIKE 'dt%'
ORDER BY ROUTINE_TYPE
	,ROUTINE_CATALOG + '.' + ROUTINE_SCHEMA + '.' + ROUTINE_NAME
	,CREATED
	,LAST_ALTERED